---
  extends: airbnb

  ecmaFeatures:
    modules: true

  env:
    es6: true
    browser: true
    node: true

  rules:
    indent: [2, 2, {"SwitchCase": 1}] # 2 spaces indentation
    max-len: [2, 80, 4, {"ignoreComments": true}]
    quotes: [2, "single"]
    semi: [2, "always"]
    no-multiple-empty-lines: [2, {"max": 1}]

    comma-dangle: [2, "always-multiline"]
    dot-location: [2, "property"]

    one-var: [2, "never"]
    no-var: [2]
    prefer-const: [2]
    no-bitwise: [2]
    id-length: ["error", {"min": 2, "properties": "never", "exceptions": ["a","b","f","x","y","i","e","d","n","_"]}]
    func-names: [0]
    no-use-before-define: [2, "nofunc"]

    object-curly-spacing: [2, "always"]
    array-bracket-spacing: [2, "never"]
    space-unary-ops: [2, {"words": true, "nonwords": false}]
    keyword-spacing: [2]
    space-before-blocks: [2, "always"]
    space-before-function-paren: [2, "never"]
    space-in-parens: [2, "never"]
    spaced-comment: [2, "always"]
