export const REQUEST_DATA = 'REQUEST_DATA';
export const RECEIVE_DATA = 'RECEIVE_DATA';
export const BUILD_SELECTOR = 'BUILD_SELECTOR';
export const UPDATE_SELECTION = 'UPDATE_SELECTION';
export const UPDATE_CURRENT_STEP = 'UPDATE_CURRENT_STEP';
export const UPDATE_IS_CUSTOMIZE_STEP = 'UPDATE_IS_CUSTOMIZE_STEP';
